### ISSUE TITLE
Can't Pack A Punch (Bug)

### ISSUE THREAD

**Issue by Swobal** [Frityet/CoDZombies-H3VR#4]
I don't know if its just because I keep trying to Pack the Tommy Gun and I just can't, or if every gun will do this. But whenever I try to slide a gun in the machine, it just clips through the machine as if it doesn't exist. I have the required points, its just that the gun clips through and the machine does nothing.

**Comment by KacperObara** [comment]
Forgot to close the issue. Thanks for feedback. Fixed in 1.0.7.
If someone is interested, it's available in develop branch. I did not make proper unity package for this. 
But it's up to date in the Thunderstore.
